### PR TITLE
Retry when rate limit exception occurs for getStreams

### LINKED ISSUE #341: Kinesis Rate Limit exceeded
## Description
When attempting to add a new Kinesis/CloudWatch input I am receiving an error after clicking "Authorize and Choose Streams". I can see this same error is logged the server.log, but no additional information before or after the error message itself. I am unable to find any AWS documentation on a limit related to Kinesis that we would potentially be hitting. Can you please advise? We are currently unable to add any new Kinesis inputs to Graylog.

> ERROR: software.amazon.awssdk.services.kinesis.model.LimitExceededException: Rate exceeded for account 943582610889. (Service: Kinesis, Status Code: 400, Request ID: dac85ac9-2965-5466-8ca3-756dbf1c2090)
## Steps To Reproduce

1. Create 200 or more streams in AWS.
1. Try to set up a new Kinesis integration.

## Environment

- Graylog Version: 3.1.3

### PR DESCRIPTION
**Pull request by danotorrey**
Fixes #341 

* Retries if Kinesis `LimitExceededException` occurs.
* Increases page size for streams from 30 to 400 to reduce the need for successive calls. Retrying successive requests will only be needed for extremely large numbers of streams.

**Ref :** 
    https://docs.aws.amazon.com/streams/latest/dev/fundamental-stream.html
    https://docs.amazonaws.cn/en_us/kinesis/latest/APIReference/kinesis-api.pdf
    https://docs.aws.amazon.com/cli/latest/reference/kinesis/create-stream.html

**CLI Reference Guide:**
https://docs.aws.amazon.com/cli/latest/reference/kinesis/describe-limits.html

**CLI-Example  for AWS services IAM(Dynamodb|Cloud Watch|Kinesis...):**
````
helium@helium-Precision-5540:~/workspace/config/shell$ aws iam get-user
{
    "User": {
        "UserName": "xxxx", 
        "PasswordLastUsed": "2019-12-12T17:00:43Z", 
        "CreateDate": "2019-11-06T14:01:44Z", 
        "UserId": "AIDAWV25I6RLUN4BMLKXB", 
        "Path": "/", 
        "Arn": "arn:aws:iam::459220251735:user/xxx"
    }
}
```

### CODE REVIEW

**Comment by danotorrey** [comment]
I need to add some comments to the code before this can be merged. I might have a chance to do that later.

File: src/main/java/org/graylog/integrations/aws/service/KinesisService.java [hunk 1]
```diff
@@ -188,12 +189,14 @@ public StreamsResponse getKinesisStreamNames(String regionName, String accessKey
         // Create retryer to keep checking if more streams exist.
         final Retryer<Boolean> retryer = RetryerBuilder.<Boolean>newBuilder()
                 .retryIfResult(b -> Objects.equals(b, Boolean.TRUE))
+                .retryIfExceptionOfType(LimitExceededException.class)
```
Comment (lingpri) [inline src/main/java/org/graylog/integrations/aws/service/KinesisService.java]: Possibly , we need to think about other ExceptionTypes, when we may want to retry.

Comment (danotorrey) [reply src/main/java/org/graylog/integrations/aws/service/KinesisService.java]: Thanks for taking a look and for the suggestion. Perhaps in the future we can expand the list to other exceptions if we know which ones they are.

Since this PR is specifically for rate limiting, I propose that we include only the `LimitExceededException` in this PR.

**Comment by danotorrey** [comment]
@lingpri @ceruleancee  I have added the needed comments. This PR is ready for review. Once merged, I will create the 3.1 backport PR.

**Comment by danotorrey** [comment]
> I will test this bugfix for LimitExceededException, in the aws_multi_auth branch.

Thank you. :) I have rebased `aws_multi_auth` #279 with master to include this fix too, so you can test it now.
